### PR TITLE
Deprecated --reverse and --subtle CSS class names in favor of clearer variants

### PR DESCRIPTION
**Pull request by scottanthonymurray**
This PR deprecates the following classes and replaces them with clearer variants:

- `.rvt-shell--reverse` ▶️ `.rvt-shell--sidebar-right`
- `.rvt-shell__stage--subtle` ▶️ `.rvt-shell__stage--gray`

See [the comments on this pull request on the `rivet-docs` repo](https://github.com/indiana-university/rivet-docs/pull/83) for more information.

### CODE REVIEW

**Comment by scottanthonymurray** [comment]
@levimcg Do you want me to go ahead and also update the documentation in this repo to match the documentation in `rivet-source`?

**Review by levimcg — APPROVED** [review]
Nice, this looks good to me.

On the docs, yeah, I guess we'll need to match the docs site. I'd like to look into a way that we can avoid duplication like this when we have the time. I'd be really interested to see if we could just write all the docs for add-ons in the repo's README and then use the GitHub API to pull that markdown into the  add-on's documentation page on `rivet-docs`.

**Comment by scottanthonymurray** [comment]
@levimcg I'll update the docs as part of this PR. I've started investigating how to pull the `README` contents via the GitHub API into the Rivet docs site, I'll open a separate PR on `rivet-docs` later this week.

**Comment by levimcg** [comment]
@scottanthonymurray Nice, thank you! 🙌

**Pull request merged**
